import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "core/index": "src/core/index.ts",
    "validators/index": "src/validators/index.ts",
    "validators/global": "src/validators/global.ts",
    "validators/in": "src/validators/in.ts",
    "validators/us": "src/validators/us.ts",
    "validators/uk": "src/validators/uk.ts",
    "validators/de": "src/validators/de.ts",
    "validators/fr": "src/validators/fr.ts",
    "validators/sg": "src/validators/sg.ts",
    "validators/ae": "src/validators/ae.ts",
    "validators/br": "src/validators/br.ts",
    "validators/au": "src/validators/au.ts",
    "validators/ca": "src/validators/ca.ts",
    "payroll/index": "src/payroll/index.ts",
    "tax/index": "src/tax/index.ts",
    "labor/index": "src/labor/index.ts",
    "banking/index": "src/banking/index.ts",
    "forms/index": "src/forms/index.ts",
    "localization/index": "src/localization/index.ts",
    "utils/index": "src/utils/index.ts",
    "types/index": "src/types/index.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  target: "es2022",
  splitting: false,
});
